[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
via_ir = true
optimizer = true
optimizer_runs = 10000



[fuzz]
runs = 256

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]